sudo: false
language: node_js
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
before_script:
  - yarn global add webpack webpack-cli
  - yarn add webpack
  - yarn install
  - yarn run test 
node_js:
  - "6"
  - "7"
